services:
  - type: web
    name: flask-proxy-browser
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: "gunicorn app:app"
    plan: free
